# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Basic.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pathlib,sqlite3
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(239, 103)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.onlyInt = QtGui.QIntValidator()
        self.stackedWidget.setCurrentIndex(0)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forgot Password"))
        self.label.setText(_translate("MainWindow", "Enter ID"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "Security Question"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Answer"))
        self.lineEdit.setValidator(self.onlyInt)
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.pushButton.clicked.connect(self.submit_id)
        self.pushButton_2.clicked.connect(self.submit_answer)

    def submit_id(self):
        data_path=pathlib.Path.cwd().joinpath('Databases')
        conn1 = sqlite3.connect(f"{data_path}/Login.db")
        cur2 = conn1.cursor()
        sql2=f'Select Question,Answer from Login_S where Roll_No = {self.lineEdit.text()}'
        if self.lineEdit.text()=='':
            popup=QMessageBox()
            popup.setWindowTitle("Forgot Password")
            popup.setText("Enter User ID in the Text Box")
            popup.setStandardButtons(QMessageBox.Ok)
            popup.setIcon(QMessageBox.Information)
            popup.exec_()
        else:
            cur2.execute(sql2)
            passw=cur2.fetchall()
            conn1.close()
            if passw==[] or passw==None:
                popup=QMessageBox()
                popup.setWindowTitle("Forgot Password")
                popup.setText("ID is not in Database")
                popup.setStandardButtons(QMessageBox.Ok)
                popup.setIcon(QMessageBox.Information)
                popup.exec_()
            else:
                temp=passw[0]
                question=temp[0]
                self.label_2.setText(question)
                self.stackedWidget.setCurrentIndex(1)
    def submit_answer(self):
        data_path=pathlib.Path.cwd().joinpath('Databases')
        conn1 = sqlite3.connect(f"{data_path}/Login.db")
        cur2 = conn1.cursor()
        sql2=f'Select Question,Answer from Login_S where Roll_No = {self.lineEdit.text()}'
        cur2.execute(sql2)
        passw=cur2.fetchall()
        
        temp=passw[0]
        answer=temp[1]
        if self.lineEdit_2.text()=='':
            popup=QMessageBox()
            popup.setWindowTitle("Forgot Password")
            popup.setText("Answer the Security Question")
            popup.setStandardButtons(QMessageBox.Ok)
            popup.setIcon(QMessageBox.Information)
            popup.exec_()
        else:
            if self.lineEdit_2.text()==answer:
                passw=subprocess.check_output([sys.executable, "Password.py"])
                passw=str(passw.decode("utf-8"))
                passw=passw[:-2]
                if passw=='':
                    pass
                else:
                    sql='''UPDATE Login_S
                        SET Password = ?
                        WHERE Roll_No = ? '''
                    data=(passw,self.lineEdit.text())
                    cur2.execute(sql,data)
                    conn1.commit()
                    conn1.close()
                    popup=QMessageBox()
                    popup.setWindowTitle("Forgot Password")
                    popup.setText("Password Has Been Reset !")
                    popup.setStandardButtons(QMessageBox.Ok)
                    popup.setIcon(QMessageBox.Information)
                    popup.exec_()
                    MainWindow.close()
             
            elif self.lineEdit_2.text()!=answer:
                popup=QMessageBox()
                popup.setWindowTitle("Forgot Password")
                popup.setText("Wrong Answer Please Try Again")
                popup.setStandardButtons(QMessageBox.Ok)
                popup.setIcon(QMessageBox.Information)
                popup.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon("logo.png"))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())