# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from subprocess import call
import subprocess

class Ui_Studentdatabase(object):
    def setupUi(self, Studentdatabase):
        Studentdatabase.setObjectName("Studentdatabase")
        Studentdatabase.resize(820, 397)
        self.gridLayoutWidget = QtWidgets.QWidget(Studentdatabase)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Studentdatabase)
        QtCore.QMetaObject.connectSlotsByName(Studentdatabase)

        #self.Enter.clicked.connect(self.enter_info)

    def retranslateUi(self, Studentdatabase):
        _translate = QtCore.QCoreApplication.translate
        Studentdatabase.setWindowTitle(_translate("Studentdatabase", "Form"))
        self.pushButton.setText(_translate("Studentdatabase", "Back"))
        self.pushButton_2.setText(_translate("Studentdatabase", "Add"))
        self.pushButton_3.setText(_translate("Studentdatabase", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Studentdatabase", "ROLL NUMBER"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Studentdatabase", "STUDENT NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Studentdatabase", "FATHER NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Studentdatabase", "CLASS ENROLL"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Studentdatabase", "GENDER"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Studentdatabase", "PHONE NUMBER"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Studentdatabase", "FATHER PHONE NUMBER"))
        self.label.setText(_translate("Studentdatabase", "Search"))
        self.pushButton_4.setText(_translate("Studentdatabase", "Enter"))
        self.pushButton.clicked.connect(self.back)

    def enter_info(self):

        self.create_database()
        get_txt =  txt_inp.toPlainText()
        #create a list of the fetch data
        data = [
            str(get_txt(input_type))
            for input_type in [
                self.RollNumber_textinp,
                self.StudentName_textinp,
                self.FatherName_textinp,
                self.PhoneNumber_textinp,
                self.FatherPhoneNumber_textinp,
                self.ClassEnroll_textinp,
                self.Gender_textinp,
                ]
            ]
        self.insert_data(data)


    def back(self):
        Studentdatabase.close()
        call(["python","Subjects_T.py"])
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Studentdatabase = QtWidgets.QWidget()
    ui = Ui_Studentdatabase()
    ui.setupUi(Studentdatabase)
    Studentdatabase.show()
    sys.exit(app.exec_())
