/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106934-ge3580f6077-20220517"
#endif /* AVUTIL_FFVERSION_H */
