# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subject(object):
    def setupUi(self, Subject):
        Subject.setObjectName("Subject")
        Subject.resize(650, 524)
        self.gridLayoutWidget = QtWidgets.QWidget(Subject)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 651, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 15)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.back.setFont(font)
        self.back.setIconSize(QtCore.QSize(16, 16))
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.delete_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout_2.addWidget(self.delete_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Subject)
        self.label.setGeometry(QtCore.QRect(410, 20, 47, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Subject)
        self.lineEdit.setGeometry(QtCore.QRect(460, 20, 181, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Subject)
        QtCore.QMetaObject.connectSlotsByName(Subject)

    def retranslateUi(self, Subject):
        _translate = QtCore.QCoreApplication.translate
        Subject.setWindowTitle(_translate("Subject", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Subject", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Subject", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Subject", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Subject", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Subject", "SUBJECT ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Subject", "SUBJECT NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Subject", "UPLOADED VIDEOS"))
        self.back.setText(_translate("Subject", "Back"))
        self.delete_2.setText(_translate("Subject", "Watch Videos"))
        self.label.setText(_translate("Subject", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subject = QtWidgets.QWidget()
    ui = Ui_Subject()
    ui.setupUi(Subject)
    Subject.show()
    sys.exit(app.exec_())
